package com.wichat.pojo;

public class WichatUser {

    /**
     * 主键id
     */
    private Integer userId;
    /**
     * 账号
     */
    private String account;
    /**
     * 密码
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wichat_user.user_id
     *
     * @return the value of wichat_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wichat_user.user_id
     *
     * @param userId the value for wichat_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wichat_user.account
     *
     * @return the value of wichat_user.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wichat_user.account
     *
     * @param account the value for wichat_user.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wichat_user.password
     *
     * @return the value of wichat_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wichat_user.password
     *
     * @param password the value for wichat_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}